db:
    type: sqlite

server:
    port: 8095

admin:
    authName: admin
    authPass: re1nF0rced

defaults:
    env:
        states:  8
        actions: 4
    spec:
        update:                       qlearn   # qlearn | sarsa
        gamma:                        0.9      # discount factor, [0, 1)
        epsilon:                      0.2      # initial epsilon for epsilon-greedy policy, [0, 1)
        alpha:                        0.005    # value function learning rate
        experience_add_every:         5        # number of time steps before we add another experience to replay memory
        experience_size:              10000    # size of experience
        learning_steps_per_iteration: 5
        tderror_clamp:                1.0      # for robustness
        num_hidden_units:             100      # number of neurons in hidden layer